"""
Harness builder for the Prove stage - builds reachability harnesses for vulnerability testing.
"""
from typing import Dict, Any, Optional
import logging
import os
from pathlib import Path

logger = logging.getLogger(__name__)


class HarnessBuilder:
    """Build reachability harnesses for vulnerability testing."""
    
    def __init__(self, work_dir: str = "/tmp/raven_harnesses"):
        """
        Initialize harness builder.
        
        Args:
            work_dir: Working directory for harness files
        """
        self.work_dir = Path(work_dir)
        self.work_dir.mkdir(parents=True, exist_ok=True)
        logger.info(f"HarnessBuilder initialized with work_dir: {self.work_dir}")
    
    def build_c_harness(
        self,
        poc_code: str,
        finding_location: str
    ) -> Dict[str, Any]:
        """
        Build C/C++ harness with sanitizers.
        
        Args:
            poc_code: PoC code to wrap in harness
            finding_location: Location of vulnerability
            
        Returns:
            Dictionary with harness build information
        """
        harness_file = self.work_dir / f"harness_{hash(finding_location)}.c"
        
        # Create harness with sanitizer instrumentation
        harness_code = f"""// Reachability harness for vulnerability at {finding_location}
// Generated by Raven Multi-Model Agentic Security Pipeline

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// PoC code
{poc_code}

int main(int argc, char **argv) {{
    printf("Reachability harness for vulnerability at {finding_location}\\n");
    
    // Call PoC function
    // This is a controlled environment for testing
    
    return 0;
}}
"""
        
        harness_file.write_text(harness_code)
        
        # Create compilation script with sanitizers
        compile_script = self.work_dir / f"compile_{hash(finding_location)}.sh"
        compile_script.write_text(f"""#!/bin/bash
# Compile harness with sanitizers

gcc -g -O0 -fsanitize=address,undefined -fno-omit-frame-pointer \\
    -o {harness_file.stem} {harness_file} \\
    -ldl -lpthread

echo "Harness compiled successfully"
""")
        
        compile_script.chmod(0o755)
        
        return {
            "harness_file": str(harness_file),
            "compile_script": str(compile_script),
            "language": "c",
            "sanitizers": ["address", "undefined"]
        }
    
    def build_rust_harness(
        self,
        poc_code: str,
        finding_location: str
    ) -> Dict[str, Any]:
        """
        Build Rust harness with sanitizers.
        
        Args:
            poc_code: PoC code to wrap in harness
            finding_location: Location of vulnerability
            
        Returns:
            Dictionary with harness build information
        """
        harness_file = self.work_dir / f"harness_{hash(finding_location)}.rs"
        
        harness_code = f"""// Reachability harness for vulnerability at {finding_location}
// Generated by Raven Multi-Model Agentic Security Pipeline

{poc_code}

fn main() {{
    println!("Reachability harness for vulnerability at {{finding_location}}");
    
    // Call PoC function
    // This is a controlled environment for testing
}}
"""
        
        harness_file.write_text(harness_code)
        
        # Create Cargo.toml for sanitizer configuration
        cargo_file = self.work_dir / "Cargo.toml"
        cargo_file.write_text("""[package]
name = "raven-harness"
version = "0.1.0"
edition = "2021"

[dependencies]

[profile.dev]
opt-level = 0
debug = true

[profile.dev.package."*"]
opt-level = 0
debug = true
""")
        
        return {
            "harness_file": str(harness_file),
            "cargo_file": str(cargo_file),
            "language": "rust",
            "sanitizers": ["address", "leak", "thread"]
        }
    
    def build_python_harness(
        self,
        poc_code: str,
        finding_location: str
    ) -> Dict[str, Any]:
        """
        Build Python harness for testing.
        
        Args:
            poc_code: PoC code to wrap in harness
            finding_location: Location of vulnerability
            
        Returns:
            Dictionary with harness build information
        """
        harness_file = self.work_dir / f"harness_{hash(finding_location)}.py"
        
        harness_code = f"""# Reachability harness for vulnerability at {finding_location}
# Generated by Raven Multi-Model Agentic Security Pipeline

import sys
import traceback

# PoC code
{poc_code}

def main():
    print(f"Reachability harness for vulnerability at {finding_location}")
    
    try:
        # Call PoC function
        # This is a controlled environment for testing
        pass
    except Exception as e:
        print(f"Error: {{e}}")
        traceback.print_exc()
        return 1
    
    return 0

if __name__ == "__main__":
    sys.exit(main())
"""
        
        harness_file.write_text(harness_code)
        
        return {
            "harness_file": str(harness_file),
            "language": "python",
            "sanitizers": []  # Python doesn't have compile-time sanitizers
        }
